### ISSUE TITLE
Your configuration contains an invalid remoteName. You should probably use one of these:

### ISSUE THREAD

**Issue by moltar** [KnisterPeter/vscode-github#642]
Failing on repos without `origin` remote:

```
Visual Studio Code GitHub Extension
git symbolic-ref -q HEAD
git --version
git for-each-ref --format='%(upstream)' 'refs/heads/feature/db-api'
git config --local --get remote.origin.url
git config --local --get-regexp ^remote.*.url
Command failed with exit code 1: git config --local --get remote.origin.url
Error: Command failed with exit code 1: git config --local --get remote.origin.url
    at makeError (/Users/user/.vscode/extensions/knisterpeter.vscode-github-0.30.3/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/user/.vscode/extensions/knisterpeter.vscode-github-0.30.3/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)


Your configuration contains an invalid remoteName. You should probably use one of these:

heroku
```

**Comment by KnisterPeter** [comment]
Good catch, I think it works with `origin` only currently

**Comment by moltar** [comment]
Not stale 😤

**Comment by KnisterPeter** [comment]
@moltar Feel free to provide a PR, I'll happy to merge
